version: '3.1'

services:
  db:
    image: postgres
    container_name: ma_postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: ma_stock
    ports:
      - 8035:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080